controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 50

    sayebot_controller:
      type: ackermann_steering_controller/AckermannSteeringController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

sayebot_controller:
  ros__parameters:
    front_steering: true
    open_loop: false
    position_feedback: true
    use_stamped_vel: true

    front_wheels_names: ["right_forward_steer_joint", "left_forward_steer_joint"]
    rear_wheels_names: ["right_backward_wheel_joint", "left_backward_wheel_joint"]
    steering_wheels_names: ["right_forward_wheel_joint", "left_forward_wheel_joint"]

    wheelbase: 0.2255
    front_wheel_track: 0.2
    rear_wheel_track: 0.2
    front_wheels_radius: 0.0365
    rear_wheels_radius: 0.0365
    wheel_separation: 0.2
    max_steering_angle: 0.5
    min_steering_angle: -0.5

    steering_slow_down_factor: 1.5
    angular_velocity_filter: 0.3

    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    cmd_vel_topic: "cmd_vel"
    cmd_type: "geometry_msgs/msg/TwistStamped"
    publish_rate: 50

    # wheel_base: 1.0
    # wheel_separation: 0.8
    # max_steering_angle: 0.5
    # max_speed: 1.0